/* The following code was generated by JFlex 1.4.1 on 5/10/24, 6:37 PM */

package dev.romainguy.kotlin.explorer.code;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 5/10/24, 6:37 PM from the specification file
 * <tt>/Users/romainguy/Source/kotlin-explorer/token-markers/src/main/java/dev/romainguy/kotlin/explorer/code/OatTokenMarker.flex</tt>
 */
public class OatTokenMarker extends AbstractJFlexTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int CODE = 2;
  public static final int FUNCTION_SIGNATURE = 6;
  public static final int YYINITIAL = 0;
  public static final int CLASS = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\17\1\16\1\0\1\17\23\0\1\17\1\0\1\13\1\11"+
    "\1\34\1\12\1\0\1\14\1\35\1\36\3\12\1\33\1\31\1\12"+
    "\1\6\1\61\1\61\1\62\1\5\1\5\1\5\1\5\1\5\1\5"+
    "\1\20\1\15\1\32\1\0\1\32\2\0\1\25\1\2\1\21\1\37"+
    "\1\73\1\55\1\101\1\65\1\57\2\1\1\23\1\77\1\51\1\63"+
    "\1\43\1\75\1\41\1\27\1\67\1\1\1\53\1\47\1\7\1\71"+
    "\1\45\1\12\1\0\1\12\1\0\1\1\1\0\1\26\1\4\1\22"+
    "\1\40\1\74\1\56\1\102\1\66\1\60\2\3\1\24\1\100\1\52"+
    "\1\64\1\44\1\76\1\42\1\30\1\70\1\3\1\54\1\50\1\10"+
    "\1\72\1\46\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\2\1\1\2\1\3\1\4\1\1\1\4\1\5"+
    "\2\6\1\1\1\5\1\7\1\10\1\11\1\1\1\5"+
    "\1\1\1\5\1\1\1\5\1\1\1\5\1\1\1\5"+
    "\1\1\1\5\1\1\1\5\1\1\1\5\1\1\1\5"+
    "\1\1\1\5\1\1\1\5\1\1\1\5\1\1\1\5"+
    "\1\1\1\5\1\1\1\5\5\1\2\0\1\12\1\0"+
    "\1\13\1\0\2\13\1\14\1\15\2\16\1\13\1\0"+
    "\1\5\1\0\1\5\2\0\2\5\1\0\1\5\3\17"+
    "\1\20\3\0\1\21\1\0\1\5\1\0\1\5\2\0"+
    "\2\5\1\1\1\22\1\0\2\23\2\0\2\5\1\24";

  private static int [] zzUnpackAction() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\103\0\206\0\311\0\u010c\0\u014f\0\u0192\0\u01d5"+
    "\0\u014f\0\u0218\0\u025b\0\u029e\0\u02e1\0\u0324\0\u0367\0\u03aa"+
    "\0\u03ed\0\u014f\0\u0430\0\u0473\0\u04b6\0\u04f9\0\u053c\0\u057f"+
    "\0\u05c2\0\u0605\0\u0648\0\u068b\0\u06ce\0\u0711\0\u0754\0\u0797"+
    "\0\u07da\0\u081d\0\u0860\0\u08a3\0\u08e6\0\u0929\0\u096c\0\u09af"+
    "\0\u09f2\0\u0a35\0\u0a78\0\u0abb\0\u0afe\0\u0b41\0\u0b84\0\u0bc7"+
    "\0\u0c0a\0\u0c4d\0\u0c90\0\u0cd3\0\u0d16\0\u0d59\0\u0d9c\0\u0ddf"+
    "\0\u0e22\0\u0e65\0\u0ea8\0\u014f\0\u0860\0\u0eeb\0\u0f2e\0\u014f"+
    "\0\u014f\0\u014f\0\u02e1\0\u02e1\0\u0f71\0\u0fb4\0\u0ff7\0\u103a"+
    "\0\u107d\0\u10c0\0\u1103\0\u1146\0\u1189\0\u11cc\0\u0c90\0\u0cd3"+
    "\0\u120f\0\u0d59\0\u1252\0\u1295\0\u12d8\0\u0ea8\0\u131b\0\u135e"+
    "\0\u13a1\0\u13e4\0\u1427\0\u146a\0\u14ad\0\u14f0\0\u1252\0\u014f"+
    "\0\u1533\0\u014f\0\u02e1\0\u1576\0\u15b9\0\u15fc\0\u163f\0\u014f";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\6\6\1\7\6\6\1\10\1\11\1\12\1\6\2\13"+
    "\66\6\1\7\6\6\1\10\1\11\1\14\1\6\2\13"+
    "\63\6\2\15\1\16\1\17\1\20\1\21\2\22\1\23"+
    "\1\24\1\10\2\22\1\6\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\22\1\6\1\22\1\6"+
    "\2\22\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\20\1\21\1\45\1\46\1\25\1\26\1\47"+
    "\1\50\1\51\1\52\2\16\1\51\1\52\1\53\1\54"+
    "\1\6\1\15\1\6\1\15\1\55\1\56\1\6\1\15"+
    "\1\57\1\60\1\61\1\62\1\6\10\63\4\6\1\10"+
    "\1\0\1\12\1\6\10\63\6\6\44\63\1\6\4\64"+
    "\2\65\2\64\4\6\1\10\1\11\1\12\1\6\10\64"+
    "\2\6\1\66\1\6\1\67\1\6\22\64\2\65\20\64"+
    "\112\0\2\70\72\0\16\10\1\0\64\10\17\0\1\12"+
    "\106\0\2\71\57\0\4\72\2\0\2\72\6\0\1\14"+
    "\1\0\10\72\6\0\22\72\2\0\20\72\3\0\2\15"+
    "\3\0\1\15\11\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\7\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\3\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\5\0\2\16\52\0\2\16"+
    "\25\0\2\16\2\73\50\0\2\16\25\0\2\74\36\0"+
    "\2\75\12\0\1\76\1\77\23\0\2\15\2\74\1\0"+
    "\1\15\11\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\7\0\1\15\1\0\1\15\1\0\1\15\1\75"+
    "\1\44\1\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\1\0\1\15\1\76\1\77\1\0\1\15\1\0"+
    "\1\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\1\0\1\15\1\0\1\15\13\23\1\100\67\23"+
    "\14\24\1\101\66\24\21\0\2\102\4\0\2\102\55\0"+
    "\2\15\3\0\1\15\10\0\1\102\1\103\1\0\1\15"+
    "\1\0\1\15\1\102\1\103\7\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\3\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\27\0\2\102"+
    "\6\0\2\102\2\74\20\0\2\102\2\0\2\102\2\0"+
    "\2\102\11\0\2\15\3\0\1\15\11\0\1\15\1\0"+
    "\1\15\1\0\1\15\1\102\1\103\6\0\1\102\1\103"+
    "\1\74\1\104\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\2\0\1\102\1\103\1\0\1\15\1\102\1\103\1\0"+
    "\1\15\1\102\1\103\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\23\0\2\102\12\0\2\105\45\0\2\15\3\0"+
    "\1\15\11\0\1\15\1\102\1\103\1\0\1\15\1\0"+
    "\1\15\6\0\1\105\1\106\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\3\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\43\0\2\74\22\0\4\102"+
    "\13\0\2\15\3\0\1\15\11\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\7\0\1\15\1\0\1\15"+
    "\1\74\1\104\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\3\0\1\15"+
    "\1\0\1\15\1\102\1\103\1\102\1\103\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\25\0\2\107"+
    "\57\0\2\15\3\0\1\15\11\0\1\15\1\0\1\15"+
    "\1\107\1\110\1\0\1\15\7\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\3\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\5\0\1\74"+
    "\53\0\1\76\1\77\23\0\2\15\1\74\2\0\1\15"+
    "\11\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\7\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\76\1\77\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\21\0\2\74\2\102\61\0"+
    "\2\15\3\0\1\15\10\0\1\74\1\104\1\102\1\103"+
    "\1\0\1\15\1\0\1\15\7\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\3\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\41\0\2\74"+
    "\43\0\2\15\3\0\1\15\11\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\7\0\1\15\1\74\1\104"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\3\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\27\0\2\111"+
    "\14\0\2\112\24\0\2\102\11\0\2\15\3\0\1\15"+
    "\11\0\1\15\1\0\1\15\1\0\1\15\1\111\1\113"+
    "\7\0\1\15\1\0\1\15\1\0\1\15\1\112\1\114"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\3\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\102\1\103\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\43\0\2\115\41\0\2\15\3\0\1\15"+
    "\11\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\7\0\1\15\1\0\1\15\1\115\1\116\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\3\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\27\0\2\111\55\0\2\15\3\0\1\15"+
    "\11\0\1\15\1\0\1\15\1\0\1\15\1\111\1\113"+
    "\7\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\3\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\27\0\2\102\26\0\2\102\25\0\2\15"+
    "\3\0\1\15\11\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\102\1\103\7\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\102\1\103\3\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\75\0\2\102\7\0\2\15"+
    "\3\0\1\15\11\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\7\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\3\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\102\1\103"+
    "\1\0\1\15\1\0\1\15\57\0\2\102\25\0\2\15"+
    "\3\0\1\15\11\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\7\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\102\1\103\3\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\67\0\2\102\2\0\2\102"+
    "\11\0\2\15\3\0\1\15\11\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\7\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\3\0\1\15"+
    "\1\0\1\15\1\102\1\103\1\0\1\15\1\102\1\103"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\12\117\1\0"+
    "\3\117\2\0\11\117\1\0\1\117\1\0\47\117\1\65"+
    "\10\120\1\65\1\0\3\65\2\0\1\65\10\120\1\121"+
    "\1\120\1\0\1\120\2\65\44\120\12\65\1\0\3\65"+
    "\2\0\11\65\1\0\1\65\1\0\47\65\1\0\10\122"+
    "\10\0\11\122\2\0\1\122\2\0\44\122\16\123\1\0"+
    "\64\123\2\0\1\124\1\0\3\124\12\0\2\124\2\0"+
    "\2\124\10\0\2\124\14\0\2\124\2\0\2\124\10\0"+
    "\2\124\33\0\2\125\55\0\10\72\10\0\11\72\5\0"+
    "\44\72\2\0\1\126\1\0\3\126\12\0\2\126\2\0"+
    "\2\126\10\0\2\126\14\0\2\126\2\0\2\126\10\0"+
    "\2\126\13\0\2\74\52\0\2\74\26\0\1\74\133\0"+
    "\2\127\45\0\2\15\3\0\1\15\11\0\1\15\1\0"+
    "\1\15\1\0\1\15\1\0\1\15\6\0\1\127\1\130"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\3\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\57\0\2\131\25\0\2\15\3\0\1\15\11\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\7\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\131\1\132"+
    "\3\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\65\0\2\133\35\0\2\134\63\0\2\15\3\0\1\15"+
    "\11\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\7\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\3\0\1\15\1\133\1\135\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\3\0\2\15\3\0\1\15\10\0\1\134"+
    "\1\136\1\0\1\15\1\0\1\15\1\0\1\15\7\0"+
    "\1\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\3\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\21\0\2\75\4\0\2\75\55\0\2\15\3\0"+
    "\1\15\10\0\1\75\1\44\1\0\1\15\1\0\1\15"+
    "\1\75\1\44\7\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\3\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\10\121\10\0\12\121"+
    "\1\0\1\121\2\0\44\121\16\123\1\0\17\123\1\137"+
    "\44\123\2\0\1\124\1\0\3\124\11\0\1\140\2\124"+
    "\2\0\2\124\10\0\2\124\14\0\2\124\2\0\2\124"+
    "\10\0\2\124\35\0\2\141\113\0\2\142\43\0\2\15"+
    "\3\0\1\15\11\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\7\0\1\15\1\142\1\143\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\3\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\55\0\2\74\27\0\2\15"+
    "\3\0\1\15\11\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\7\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\74\1\104\1\0\1\15\3\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\23\0\2\144\2\0\2\145"+
    "\125\0\2\74\31\0\2\15\3\0\1\15\11\0\1\15"+
    "\1\144\1\146\1\0\1\15\1\145\1\147\7\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\3\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\3\0\2\15\3\0\1\15\11\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\7\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\74\1\104\1\0\1\15\1\0\1\15\3\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\1\15\1\0\1\15\27\0\2\150"+
    "\111\0\2\102\131\0\2\102\15\0\2\15\3\0\1\15"+
    "\11\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15"+
    "\6\0\1\102\1\103\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\1\0\1\15\3\0\1\15\1\0\1\15\1\0"+
    "\1\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\1\0\1\15\3\0\2\15\3\0\1\15\11\0"+
    "\1\15\1\0\1\15\1\0\1\15\1\0\1\15\7\0"+
    "\1\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\3\0\1\15\1\0\1\15\1\102\1\103\1\0"+
    "\1\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5762];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\5\0\1\11\2\1\1\11\10\1\1\11\45\1\2\0"+
    "\1\1\1\0\1\11\1\0\2\1\3\11\2\1\1\0"+
    "\1\1\1\0\1\1\2\0\2\1\1\0\5\1\3\0"+
    "\1\1\1\0\1\1\1\0\1\1\2\0\3\1\1\11"+
    "\1\0\1\11\1\1\2\0\2\1\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[104];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */
    public OatTokenMarker() {
        super();
    }

    private void addToken(int tokenType) {
        addToken(zzStartRead, zzMarkedPos-1, tokenType);
    }

    private void addToken(int start, int end, int tokenType) {
        int so = start + offsetShift;
        addToken(zzBuffer, start,end, tokenType, so);
    }

    @Override
    public void addToken(char[] array, int start, int end, int tokenType, int startOffset) {
        super.addToken(array, start,end, tokenType, startOffset);
        zzStartRead = zzMarkedPos;
    }

    @Override
    public String[] getLineCommentStartAndEnd(int languageIndex) {
        return new String[] { ";", null };
    }

    public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

        resetTokenList();
        this.offsetShift = -text.offset + startOffset;

        // Start off in the proper state.
        int state = Token.NULL;

        s = text;
        try {
            yyreset(zzReader);
            yybegin(state);
            return yylex();
        } catch (IOException ioe) {
            ioe.printStackTrace();
            return new TokenImpl();
        }

    }

    private boolean zzRefill() {
        return zzCurrentPos>=s.offset+s.count;
    }

    public final void yyreset(Reader reader) {
        // 's' has been updated.
        zzBuffer = s.array;
        /*
         * We replaced the line below with the two below it because zzRefill
         * no longer "refills" the buffer (since the way we do it, it's always
         * "full" the first time through, since it points to the segment's
         * array).  So, we assign zzEndRead here.
         */
        //zzStartRead = zzEndRead = s.offset;
        zzStartRead = s.offset;
        zzEndRead = zzStartRead + s.count - 1;
        zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
        zzLexicalState = YYINITIAL;
        zzReader = reader;
        zzAtBOL  = true;
        zzAtEOF  = false;
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public OatTokenMarker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public OatTokenMarker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 186) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */



  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { addNullToken(); return firstToken;
          }
        case 21: break;
        case 13: 
          { addToken(Token.LITERAL_CHAR);
          }
        case 22: break;
        case 16: 
          { addToken(Token.COMMENT_MULTILINE);
          }
        case 23: break;
        case 4: 
          { addToken(Token.WHITESPACE);
          }
        case 24: break;
        case 17: 
          { addToken(Token.LITERAL_NUMBER_HEXADECIMAL);
          }
        case 25: break;
        case 10: 
          { addToken(Token.DATA_TYPE);
        yybegin(FUNCTION_SIGNATURE);
          }
        case 26: break;
        case 5: 
          { addToken(Token.RESERVED_WORD);
          }
        case 27: break;
        case 11: 
          { addToken(Token.VARIABLE);
          }
        case 28: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 29: break;
        case 15: 
          { addToken(Token.FUNCTION);
          }
        case 30: break;
        case 8: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 31: break;
        case 19: 
          { addToken(Token.DATA_TYPE);
          }
        case 32: break;
        case 9: 
          { addToken(Token.ERROR_CHAR);
          }
        case 33: break;
        case 20: 
          { addToken(Token.RESERVED_WORD); yybegin(CLASS);
          }
        case 34: break;
        case 12: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 35: break;
        case 2: 
          { addToken(Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 36: break;
        case 14: 
          { addToken(Token.RESERVED_WORD_2);
          }
        case 37: break;
        case 18: 
          { addToken(Token.PREPROCESSOR); yybegin(CODE);
          }
        case 38: break;
        case 6: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 39: break;
        case 7: 
          { addToken(Token.OPERATOR);
          }
        case 40: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case CODE: {
              addNullToken(); return firstToken;
            }
            case 105: break;
            case FUNCTION_SIGNATURE: {
              addNullToken(); return firstToken;
            }
            case 106: break;
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 107: break;
            case CLASS: {
              addNullToken(); return firstToken;
            }
            case 108: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
